find_package(clog)
find_path(XS_INCLUDE_DIR crosssocket.h /usr/local/include /usr/include $ENV{crosssocket_DIR}/include)
find_library(XS_LIBS crosssocket /usr/local/lib /usr/lib $ENV{crosssocket_DIR}/lib)
get_filename_component(XS_LIBRARY_DIR ${XS_LIBS} PATH)
if(XS_INCLUDE_DIR)
	if(XS_LIBS)
		set(XS_FOUND "YES")
		if (WIN32)
			set(XS_LIBS ${XS_LIBS} wsock32 ws2_32)
		endif ()
		set(XS_LIBS ${XS_LIBS} ${CLOG_LIBS})
	endif()
endif()
